### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by acorncom** [BBVAEngineering/ember-cli-qunit-parameterize#1]
Howdy, this add-on looks like something I'd love to use as well. Do you have rough notes on how to go about using it in a consuming app?  Happy to put the time in on a PR to document it well if you have basic instructions. 

Thanks!

**Comment by adrigzr** [comment]
Hi @acorncom,

This addon will just setup [qunit-parameterize](https://github.com/AStepaniuk/qunit-parameterize) on the project and will export it as `qunit-parameterize` module. So, to use it, you just need to set it up this way:

```
import cases from 'qunit-parameterize';

cases([
  a: 1,
  b: 2
]).test('foo title', (params, assert) => {
  assert.equal(params.a, 1);
  assert.equal(params.b, 2);
});
```

For more information about [qunit-parameterize](https://github.com/AStepaniuk/qunit-parameterize) usage, check the link.

It would be great if you could update the documentation! :)

Thanks and regards.
